sudo: required

services:
  - docker

jobs:
  include:
    - stage: build docker test image
      script:
        - git checkout ${TRAVIS_BRANCH}
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - make IMAGE_REPO=$DOCKER_USERNAME IMAGE_TAG=travis-${TRAVIS_COMMIT} build_test_image
        - docker images
        - make IMAGE_REPO=$DOCKER_USERNAME IMAGE_TAG=travis-${TRAVIS_COMMIT} push_test_image
    - stage: test
      script:
        - docker run -e COVERALLS_TOKEN=${COVERALLS_TOKEN}
          --rm ${DOCKER_USERNAME}/ubuntu-setup-test:travis-${TRAVIS_COMMIT}
    - stage: build and deploy images
      script:
        - git checkout ${TRAVIS_BRANCH}
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - make IMAGE_REPO=${DOCKER_USERNAME} IMAGE_TAG=${TRAVIS_COMMIT}
        - docker images
        - make IMAGE_REPO=${DOCKER_USERNAME} IMAGE_TAG=${TRAVIS_COMMIT} push

notifications:
  email: false

branches:
  except:
  - legacy

# safelist
branches:
  only:
  - master
  - /experimental(-.*)?/
  - stable
